package My_moon_period_tracker.demo.Enums;

public enum Emotion {

    CALM, HAPPY, ENERGETIC, FRISKY, MOOD_SWINGS, IRRITATED, SAD, ANXIOUS, DEPRESSED, GUILT, OBSESSIVE_THOUGHTS, APATHETIC, CONFUSED, SELF_CRITICAL

}
